/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmColores.java
 *
 * Created on 12-02-2011, 11:17:32 AM
 */
package uno;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author DAVID
 */
public class FrmColores extends javax.swing.JDialog {
    public Colores colorSelecc ;
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form FrmColores */
    public FrmColores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setSize(412, 434);            
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        jAmarillo.setIcon(Imagenes.ColorTriangAmarillo());
        jAzul.setIcon(Imagenes.ColorTriangAzul());
        jRojo.setIcon(Imagenes.ColorTriangRojo());
        jVerde.setIcon(Imagenes.ColorTriangVerde());
        
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        //this.setLocationByPlatform(true);
        
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        
       // this.setLocationRelativeTo(null);
        
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jVerde = new javax.swing.JLabel();
        jAzul = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        jAmarillo = new javax.swing.JLabel();
        jRojo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno.UnoApp.class).getContext().getResourceMap(FrmColores.class);
        jVerde.setIcon(resourceMap.getIcon("jVerde.icon")); // NOI18N
        jVerde.setText(resourceMap.getString("jVerde.text")); // NOI18N
        jVerde.setName("jVerde"); // NOI18N
        jVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVerdeMouseClicked(evt);
            }
        });
        getContentPane().add(jVerde);
        jVerde.setBounds(270, 180, 110, 110);

        jAzul.setIcon(resourceMap.getIcon("jAzul.icon")); // NOI18N
        jAzul.setName("jAzul"); // NOI18N
        jAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAzulMouseClicked(evt);
            }
        });
        getContentPane().add(jAzul);
        jAzul.setBounds(160, 290, 110, 110);

        jLogo.setIcon(resourceMap.getIcon("jLogo.icon")); // NOI18N
        jLogo.setName("jLogo"); // NOI18N
        jLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoMouseClicked(evt);
            }
        });
        getContentPane().add(jLogo);
        jLogo.setBounds(160, 180, 110, 110);

        jAmarillo.setIcon(resourceMap.getIcon("jAmarillo.icon")); // NOI18N
        jAmarillo.setName("jAmarillo"); // NOI18N
        jAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAmarilloMouseClicked(evt);
            }
        });
        getContentPane().add(jAmarillo);
        jAmarillo.setBounds(160, 70, 110, 110);

        jRojo.setIcon(null);
        jRojo.setName("jRojo"); // NOI18N
        jRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRojoMouseClicked(evt);
            }
        });
        getContentPane().add(jRojo);
        jRojo.setBounds(50, 180, 110, 110);

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
        
    }//GEN-LAST:event_closeDialog

private void jAmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAmarilloMouseClicked
colorSelecc = Colores.Amarillo;
this.dispose();
}//GEN-LAST:event_jAmarilloMouseClicked

private void jVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVerdeMouseClicked
colorSelecc = Colores.Verde;
this.dispose();
}//GEN-LAST:event_jVerdeMouseClicked

private void jLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoMouseClicked

}//GEN-LAST:event_jLogoMouseClicked

private void jAzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAzulMouseClicked
colorSelecc = Colores.Azul;
this.dispose();
}//GEN-LAST:event_jAzulMouseClicked

private void jRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRojoMouseClicked
colorSelecc = Colores.Rojo;
this.dispose();
}//GEN-LAST:event_jRojoMouseClicked
    
    private void doClose(int retStatus) {
        if (colorSelecc ==null)
        {
            return;
        }
        
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmColores dialog = new FrmColores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAmarillo;
    private javax.swing.JLabel jAzul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jRojo;
    private javax.swing.JLabel jVerde;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
