/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmUsuarios.java
 *
 * Created on 11-03-2011, 06:15:40 PM
 */
package uno;

import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;


public class FrmUsuarios extends javax.swing.JFrame {

    public String FileNamePartida="";
    private boolean nuevojuego ;
    private boolean CargarPartida ;
    public FrmUsuarios(boolean nuevoJuego,boolean CargarPartida) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.nuevojuego=nuevoJuego;
        this.CargarPartida=CargarPartida;
        //jAddUser.setVisible(!nuevoJuego);
        this.jInicio.setVisible(true);
        jInicio.setIcon(Imagenes.Home());
        cargar();
    }
    
   public FrmUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);        
        this.nuevojuego=false;
        this.CargarPartida=false;
        //jAddUser.setVisible(!nuevojuego);
        this.jInicio.setVisible(!nuevojuego);
        jInicio.setIcon(Imagenes.Home());
        cargar();
    }
   
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        jAddUser = new javax.swing.JLabel();
        jInicio = new javax.swing.JLabel();
        jcontinuar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno.UnoApp.class).getContext().getResourceMap(FrmUsuarios.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBounds(new java.awt.Rectangle(5, 5, 10, 10));
        setMinimumSize(new java.awt.Dimension(712, 690));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jPanel2.border.lineColor"), 3, true)); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jScrollPane2.setBackground(resourceMap.getColor("jScrollPane2.background")); // NOI18N
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFocusTraversalPolicyProvider(true);
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setAutoscrolls(true);
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);
        jScrollPane2.setViewportView(jPanel1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 690, 490);

        banner.setIcon(resourceMap.getIcon("banner.icon")); // NOI18N
        banner.setName("banner"); // NOI18N
        banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bannerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bannerMouseExited(evt);
            }
        });
        jPanel2.add(banner);
        banner.setBounds(5, 1, 700, 60);

        jAddUser.setFont(resourceMap.getFont("jAddUser.font")); // NOI18N
        jAddUser.setForeground(resourceMap.getColor("jAddUser.foreground")); // NOI18N
        jAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddUser.setIcon(resourceMap.getIcon("jAddUser.icon")); // NOI18N
        jAddUser.setText(resourceMap.getString("jAddUser.text")); // NOI18N
        jAddUser.setToolTipText(resourceMap.getString("jAddUser.toolTipText")); // NOI18N
        jAddUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jAddUser.setName("jAddUser"); // NOI18N
        jAddUser.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddUserMouseExited(evt);
            }
        });
        jPanel2.add(jAddUser);
        jAddUser.setBounds(150, 75, 60, 70);

        jInicio.setFont(resourceMap.getFont("jInicio.font")); // NOI18N
        jInicio.setForeground(resourceMap.getColor("jInicio.foreground")); // NOI18N
        jInicio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jInicio.setIcon(resourceMap.getIcon("jInicio.icon")); // NOI18N
        jInicio.setText(resourceMap.getString("jInicio.text")); // NOI18N
        jInicio.setToolTipText(resourceMap.getString("jInicio.toolTipText")); // NOI18N
        jInicio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jInicio.setName("jInicio"); // NOI18N
        jInicio.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jInicioMouseExited(evt);
            }
        });
        jPanel2.add(jInicio);
        jInicio.setBounds(10, 75, 50, 70);

        jcontinuar.setFont(resourceMap.getFont("jcontinuar.font")); // NOI18N
        jcontinuar.setForeground(resourceMap.getColor("jcontinuar.foreground")); // NOI18N
        jcontinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcontinuar.setIcon(resourceMap.getIcon("jcontinuar.icon")); // NOI18N
        jcontinuar.setText(resourceMap.getString("jcontinuar.text")); // NOI18N
        jcontinuar.setToolTipText(resourceMap.getString("jcontinuar.toolTipText")); // NOI18N
        jcontinuar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jcontinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jcontinuar.setName("jcontinuar"); // NOI18N
        jcontinuar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jcontinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcontinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcontinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcontinuarMouseExited(evt);
            }
        });
        jPanel2.add(jcontinuar);
        jcontinuar.setBounds(70, 75, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void cargar()
   {
       
    int y=5,x=5;
    for (Usuarios u:ControlUsuarios.GetDisponibles()){
        
        if (!u.Activo){continue;}
        
        ucJugadores uc = new ucJugadores(u.nombre, String.valueOf(u.edad), String.valueOf(u.sexo),u.Foto,u.cod,nuevojuego,u.puntos);
        
        
        uc.setSize(325,208);
        
           if (x==5)
           {
               uc.setLocation(5, y );
               x+=325;
              // y=0;
           }
           else
           {
               uc.setLocation(x +5 , y);
               x=5;
               y+=210;
           }
           
     
        jPanel1.add(uc);
    
    }

        jPanel1.revalidate();
        jPanel1.repaint();
        
        
        jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        //jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(false);
        
   }
   
   private void continuar() throws FileNotFoundException, IOException
   {
    
    ArrayList<ucJugadores> jugs= new ArrayList<ucJugadores>();
    ArrayList<ucJugadores> eliminados= new ArrayList<ucJugadores>();
    
    
    for (Component c : jPanel1.getComponents())
    {
        if (c instanceof ucJugadores)
        {
            if ( ((ucJugadores)(c)).seleccionado)
            {
                jugs.add( (ucJugadores)c );
            }
            else if ( ((ucJugadores)(c)).eliminado)
            {
                eliminados.add( (ucJugadores)c );
            }
        }
    }
    
    if (nuevojuego)
    {
        if (jugs.size()>0 && jugs.size()==2 )
        {

                Util.jugadores = new Jugador[ jugs.size()+1 ] ;

                int index=0;

                for (ucJugadores uc:jugs)
                {
                    //los puntos deben comenzar desde cero por cada juego y luego sumarse
                    Util.jugadores[index]= new Jugador(uc.Nombre() , uc.Genero(), uc.Foto(), uc.Edad(), uc.Codigo(),true,false,0);
                    index++;
                }
                    
                if (CargarPartida){
                     frmTablero t = new frmTablero(FileNamePartida);
                    t.setVisible(true);
                    this.dispose();
                }
                else{
                    frmTablero t = new frmTablero();
                    t.setVisible(true);
                    this.dispose();
                }
                
        }else if (jugs.size()>2)
        {

                Util.Messaje("Actualmente solo tenemos soporte para dos jugadores.");
                return;

        }else
        {

                Util.Messaje("Debes seleccionar dos jugadores.");
                return;
        }
    
    }
    else
    {
        if (eliminados.size()>0)
        {
            if ((JOptionPane.showConfirmDialog(this, "Algunos jugadores estan en la lista negra,Confirmar eliminación?"))==0)
            {
                for (ucJugadores j:eliminados)
                {
                     if (!(ControlUsuarios.Inactivar(j.Nombre())))
                     {
                         Util.Messaje("Jugador +" +j.Nombre() + " no se pudo eliminar");
                     }
                }
                
                               
                //Util.Messaje("Jugadores eliminados"); 
                this.dispose();
                MENU m = new MENU();
                m.setVisible(true);
            }
        }
        else
        {
            this.dispose();
            MENU m = new MENU();
            m.setVisible(true);
        }
    }
       
   }
private void bannerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMouseEntered

}//GEN-LAST:event_bannerMouseEntered

private void bannerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMouseExited

}//GEN-LAST:event_bannerMouseExited

private void jAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddUserMouseClicked
  FrmUsuariosAdd f = new FrmUsuariosAdd(nuevojuego,CargarPartida);
  f.setVisible(true);
  this.dispose();
}//GEN-LAST:event_jAddUserMouseClicked

private void jAddUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddUserMouseEntered
    jAddUser.setIcon(Imagenes.AddUserOver());
    
}//GEN-LAST:event_jAddUserMouseEntered

private void jAddUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddUserMouseExited
    jAddUser.setIcon(Imagenes.AddUser());
}//GEN-LAST:event_jAddUserMouseExited

private void jInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicioMouseClicked
  
  MENU m = new MENU();
  m.setVisible(true);
  this.dispose();
}//GEN-LAST:event_jInicioMouseClicked

private void jInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicioMouseEntered
jInicio.setIcon(Imagenes.HomeOver());
}//GEN-LAST:event_jInicioMouseEntered

private void jInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicioMouseExited
 jInicio.setIcon(Imagenes.Home());
}//GEN-LAST:event_jInicioMouseExited

private void jcontinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcontinuarMouseClicked
        try {
            continuar();
        } catch (Exception ex) {
           Util.Messaje(ex.getMessage());
        }
}//GEN-LAST:event_jcontinuarMouseClicked

private void jcontinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcontinuarMouseEntered
    jcontinuar.setIcon(Imagenes.NextOver());
}//GEN-LAST:event_jcontinuarMouseEntered

private void jcontinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcontinuarMouseExited
    jcontinuar.setIcon(Imagenes.Next());
}//GEN-LAST:event_jcontinuarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JLabel jAddUser;
    private javax.swing.JLabel jInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jcontinuar;
    // End of variables declaration//GEN-END:variables
}
