/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmUsuariosAdd.java
 *
 * Created on 11-01-2011, 09:31:28 PM
 */
package uno;

import javax.swing.ImageIcon;


public class FrmUsuariosAdd extends javax.swing.JFrame {
    private String pathfoto;
    private boolean juegonuevo ;
    private boolean CargarPartida;
    /** Creates new form FrmUsuariosAdd */
    public FrmUsuariosAdd( boolean esJuegoNuevo,boolean CargarPartida) {
        initComponents();
      //  jTextField1.setBorder(new Redondear(true));
        this.juegonuevo=esJuegoNuevo;
        this.CargarPartida =CargarPartida;
        this.setLocationRelativeTo(null);
        Limpiar();
        jLabel3.setIcon(Imagenes.MenuPJugadores());
        jLabel2.setIcon(Imagenes.MenuSalirOver());
        
        jAdd.setIcon(Imagenes.ColorAddFoto());
        jremove.setIcon(Imagenes.ColorRevFoto());
        this.setSize(470, 400);
        this.setResizable(false);
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPaintingUtils1 = new org.pushingpixels.substance.internal.painter.BackgroundPaintingUtils();
        lightAquaColorScheme1 = new org.pushingpixels.substance.api.colorscheme.LightAquaColorScheme();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jpicture = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFemenino = new javax.swing.JRadioButton();
        jMasculino = new javax.swing.JRadioButton();
        banner = new javax.swing.JLabel();
        jremove = new javax.swing.JLabel();
        jAdd = new javax.swing.JLabel();
        jedad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno.UnoApp.class).getContext().getResourceMap(FrmUsuariosAdd.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBounds(new java.awt.Rectangle(5, 6, 3, 4));
        setMinimumSize(new java.awt.Dimension(455, 335));
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                AbrirMenu(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(455, 335));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(455, 335));
        jPanel1.setLayout(null);

        jpicture.setBackground(resourceMap.getColor("jpicture.background")); // NOI18N
        jpicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpicture.setIcon(resourceMap.getIcon("jpicture.icon")); // NOI18N
        jpicture.setText(resourceMap.getString("jpicture.text")); // NOI18N
        jpicture.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jpicture.border.lineColor"), 2, true)); // NOI18N
        jpicture.setName("jpicture"); // NOI18N
        jPanel1.add(jpicture);
        jpicture.setBounds(50, 80, 168, 206);

        jnombre.setBackground(resourceMap.getColor("jnombre.background")); // NOI18N
        jnombre.setFont(resourceMap.getFont("jnombre.font")); // NOI18N
        jnombre.setForeground(resourceMap.getColor("jnombre.foreground")); // NOI18N
        jnombre.setText(resourceMap.getString("jnombre.text")); // NOI18N
        jnombre.setBorder(new javax.swing.border.LineBorder(resourceMap.getColor("jnombre.border.lineColor"), 2, true)); // NOI18N
        jnombre.setName("jnombre"); // NOI18N
        jPanel1.add(jnombre);
        jnombre.setBounds(230, 110, 167, 36);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setNextFocusableComponent(jnombre);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 320, 215, 40);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(resourceMap.getString("jLabel3.toolTipText")); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setNextFocusableComponent(jLabel2);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(15, 320, 215, 40);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 80, 62, 22);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 220, 60, 24);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 150, 42, 24);

        jFemenino.setBackground(resourceMap.getColor("jFemenino.background")); // NOI18N
        buttonGroup1.add(jFemenino);
        jFemenino.setText(resourceMap.getString("jFemenino.text")); // NOI18N
        jFemenino.setName("jFemenino"); // NOI18N
        jPanel1.add(jFemenino);
        jFemenino.setBounds(320, 250, 80, 23);

        jMasculino.setBackground(resourceMap.getColor("jMasculino.background")); // NOI18N
        buttonGroup1.add(jMasculino);
        jMasculino.setSelected(true);
        jMasculino.setText(resourceMap.getString("jMasculino.text")); // NOI18N
        jMasculino.setName("jMasculino"); // NOI18N
        jMasculino.setNextFocusableComponent(jFemenino);
        jPanel1.add(jMasculino);
        jMasculino.setBounds(230, 250, 80, 23);

        banner.setIcon(resourceMap.getIcon("banner.icon")); // NOI18N
        banner.setText(resourceMap.getString("banner.text")); // NOI18N
        banner.setName("banner"); // NOI18N
        banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bannerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bannerMouseExited(evt);
            }
        });
        jPanel1.add(banner);
        banner.setBounds(0, 0, 460, 60);

        jremove.setIcon(resourceMap.getIcon("jremove.icon")); // NOI18N
        jremove.setText(resourceMap.getString("jremove.text")); // NOI18N
        jremove.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jremove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jremove.setName("jremove"); // NOI18N
        jremove.setVerifyInputWhenFocusTarget(false);
        jremove.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jremoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jremoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jremoveMouseExited(evt);
            }
        });
        jPanel1.add(jremove);
        jremove.setBounds(19, 110, 30, 10);

        jAdd.setIcon(resourceMap.getIcon("jAdd.icon")); // NOI18N
        jAdd.setName("jAdd"); // NOI18N
        jAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAddMouseExited(evt);
            }
        });
        jPanel1.add(jAdd);
        jAdd.setBounds(23, 80, 25, 20);

        jedad.setName("jedad"); // NOI18N
        jPanel1.add(jedad);
        jedad.setBounds(230, 180, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar()
    {
        jnombre.setText("");
        jAdd.setVisible(true);
        jremove.setVisible(false);
        jpicture.setIcon(Imagenes.UsuarioAnonimo());
        
        buttonGroup1.setSelected(jMasculino.getModel(),false);
        buttonGroup1.setSelected(jFemenino.getModel(),false);
        pathfoto="";
        //jedad.setText("");
       jedad.setValue(25);
    }
    
    
private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    if (jnombre.getText().length()<=0)
    {
        Util.Messaje(this,"Escribir nombre");
        return;
    }
    
    
//    if (jedad.getValue().toString().length().length()<=0)
//    {
//        Util.Messaje(this,"Escribir edad");
//        return;
//    }
    
  if (  ControlUsuarios.Agregar(this,jnombre.getText(),pathfoto , 
            (buttonGroup1.isSelected(jMasculino.getModel())?'H':'F'), Integer.valueOf(jedad.getValue().toString())
        )){
      Limpiar();
      
}
}//GEN-LAST:event_jLabel3MouseClicked


private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
 jLabel3.setIcon(Imagenes.MenuPJugadoresOver());
 
}//GEN-LAST:event_jLabel3MouseEntered

private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
jLabel3.setIcon(Imagenes.MenuPJugadores());

}//GEN-LAST:event_jLabel3MouseExited

private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
 jLabel2.setIcon(Imagenes.MenuSalir());
}//GEN-LAST:event_jLabel2MouseEntered

private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
jLabel2.setIcon(Imagenes.MenuSalirOver());
}//GEN-LAST:event_jLabel2MouseExited

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 //if (JOptionPane.showConfirmDialog(this, "Deseas cancelar?") ==0)
// {
     FrmUsuarios f = new FrmUsuarios(juegonuevo,CargarPartida);
     f.setVisible(true);
     this.dispose();
 //}
}//GEN-LAST:event_jLabel2MouseClicked

private void bannerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMouseEntered

}//GEN-LAST:event_bannerMouseEntered

private void bannerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMouseExited

}//GEN-LAST:event_bannerMouseExited

private void jremoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jremoveMouseEntered
jremove.setIcon(Imagenes.ColorRevFotoOver());
}//GEN-LAST:event_jremoveMouseEntered

private void jremoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jremoveMouseExited
jremove.setIcon(Imagenes.ColorRevFoto());
}//GEN-LAST:event_jremoveMouseExited

private void jremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jremoveMouseClicked
jpicture.setIcon(Imagenes.UsuarioAnonimo());
jremove.setVisible(false);
pathfoto="";
}//GEN-LAST:event_jremoveMouseClicked

private void jAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddMouseClicked
 
 Imagenes img = new Imagenes();
 
 ImageIcon icon = img.getFoto(jpicture);
 pathfoto=img.fotopath;
 
 if (!(icon == null))
 {
     jremove.setVisible(true);
     jpicture.setIcon(icon);
     
     
 }
}//GEN-LAST:event_jAddMouseClicked

private void jAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddMouseEntered
jAdd.setIcon(Imagenes.ColorAddFotoOver());
}//GEN-LAST:event_jAddMouseEntered

private void jAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddMouseExited
jAdd.setIcon(Imagenes.ColorAddFoto());
}//GEN-LAST:event_jAddMouseExited

private void AbrirMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AbrirMenu
 
}//GEN-LAST:event_AbrirMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmUsuariosAdd(true,false).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.pushingpixels.substance.internal.painter.BackgroundPaintingUtils backgroundPaintingUtils1;
    private javax.swing.JLabel banner;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAdd;
    private javax.swing.JRadioButton jFemenino;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jMasculino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jedad;
    private javax.swing.JTextField jnombre;
    private javax.swing.JLabel jpicture;
    private javax.swing.JLabel jremove;
    private org.pushingpixels.substance.api.colorscheme.LightAquaColorScheme lightAquaColorScheme1;
    // End of variables declaration//GEN-END:variables
}
