/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MENU.java
 *
 * Created on 11-02-2011, 10:53:40 PM
 */
package uno;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class MENU extends javax.swing.JFrame {

    /** Creates new form MENU */
    public MENU(){
        try {
            initComponents();
            this.setSize(1066,530);
            this.setResizable(false);
            this.setLocationRelativeTo(null);
            ControlUsuarios.configFiles();
            Partidas.configFiles();
    //        colocar en full screen
    //        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    //        GraphicsDevice screen = ge.getDefaultScreenDevice();
    //    
    //        BufferedImage loadedpic = ImageIO.read(new File("img//MENU.JPG"));        
    //        screen.setFullScreenWindow(this);
           
    //          salir de full screen
    //         GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    //         GraphicsDevice gs = ge.getDefaultScreenDevice();
    //     
    //
        } catch (Exception ex) {
            Util.Messaje(ex.getMessage());
            this.dispose();
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jJugar = new javax.swing.JLabel();
        jJugadores = new javax.swing.JLabel();
        jtop10 = new javax.swing.JLabel();
        jJugar3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno.UnoApp.class).getContext().getResourceMap(MENU.class);
        jJugar.setFont(resourceMap.getFont("jJugar.font")); // NOI18N
        jJugar.setForeground(resourceMap.getColor("jJugar.foreground")); // NOI18N
        jJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJugar.setIcon(resourceMap.getIcon("jJugar.icon")); // NOI18N
        jJugar.setText(resourceMap.getString("jJugar.text")); // NOI18N
        jJugar.setToolTipText(resourceMap.getString("jJugar.toolTipText")); // NOI18N
        jJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jJugar.setName("jJugar"); // NOI18N
        jJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jJugarMouseExited(evt);
            }
        });
        getContentPane().add(jJugar);
        jJugar.setBounds(30, 120, 210, 50);

        jJugadores.setFont(resourceMap.getFont("jJugadores.font")); // NOI18N
        jJugadores.setForeground(resourceMap.getColor("jJugadores.foreground")); // NOI18N
        jJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/resources/azulm.png"))); // NOI18N
        jJugadores.setText(resourceMap.getString("jJugadores.text")); // NOI18N
        jJugadores.setToolTipText(resourceMap.getString("jJugadores.toolTipText")); // NOI18N
        jJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jJugadores.setName("jJugadores"); // NOI18N
        jJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJugadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jJugadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jJugadoresMouseExited(evt);
            }
        });
        getContentPane().add(jJugadores);
        jJugadores.setBounds(100, 190, 210, 50);

        jtop10.setFont(resourceMap.getFont("jtop10.font")); // NOI18N
        jtop10.setForeground(resourceMap.getColor("jtop10.foreground")); // NOI18N
        jtop10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtop10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/resources/morado.png"))); // NOI18N
        jtop10.setText(resourceMap.getString("jtop10.text")); // NOI18N
        jtop10.setToolTipText(resourceMap.getString("jtop10.toolTipText")); // NOI18N
        jtop10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtop10.setName("jtop10"); // NOI18N
        jtop10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtop10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtop10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtop10MouseExited(evt);
            }
        });
        getContentPane().add(jtop10);
        jtop10.setBounds(170, 260, 210, 50);

        jJugar3.setFont(resourceMap.getFont("jJugar3.font")); // NOI18N
        jJugar3.setForeground(resourceMap.getColor("jJugar3.foreground")); // NOI18N
        jJugar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jJugar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/resources/rojom.png"))); // NOI18N
        jJugar3.setText(resourceMap.getString("jJugar3.text")); // NOI18N
        jJugar3.setToolTipText(resourceMap.getString("jJugar3.toolTipText")); // NOI18N
        jJugar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jJugar3.setName("jJugar3"); // NOI18N
        jJugar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJugar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jJugar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jJugar3MouseExited(evt);
            }
        });
        getContentPane().add(jJugar3);
        jJugar3.setBounds(270, 330, 210, 50);

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugarMouseEntered
    jJugar.setIcon(Imagenes.MenuPNuevoJuegoOver());
}//GEN-LAST:event_jJugarMouseEntered

private void jJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugarMouseExited
    jJugar.setIcon(Imagenes.MenuPNuevoJuego());
}//GEN-LAST:event_jJugarMouseExited

private void jJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugadoresMouseEntered
    jJugadores.setIcon(Imagenes.MenuPJugadoresOver());
}//GEN-LAST:event_jJugadoresMouseEntered

private void jJugadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugadoresMouseExited
    jJugadores.setIcon(Imagenes.MenuPJugadores());
}//GEN-LAST:event_jJugadoresMouseExited

private void jtop10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtop10MouseEntered
    jtop10.setIcon(Imagenes.MenuPTop10Over());
}//GEN-LAST:event_jtop10MouseEntered

private void jtop10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtop10MouseExited
    jtop10.setIcon(Imagenes.MenuPTop10());
}//GEN-LAST:event_jtop10MouseExited

private void jJugar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugar3MouseEntered
    jJugar3.setIcon(Imagenes.MenuSalirOver());
}//GEN-LAST:event_jJugar3MouseEntered

private void jJugar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugar3MouseExited
    jJugar3.setIcon(Imagenes.MenuSalir());
}//GEN-LAST:event_jJugar3MouseExited

private void jJugar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugar3MouseClicked
 if (JOptionPane.showConfirmDialog(this,"Deseas salir del juego?")==0)
 {
     this.dispose();
 }
}//GEN-LAST:event_jJugar3MouseClicked

private void jJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugarMouseClicked
 FrmNuevoJuego f= new FrmNuevoJuego();
 f.setVisible(true); 
 this.dispose();
}//GEN-LAST:event_jJugarMouseClicked

private void jJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJugadoresMouseClicked
 FrmUsuarios f= new FrmUsuarios(false,false);
 f.setVisible(true);
 this.dispose();
}//GEN-LAST:event_jJugadoresMouseClicked

private void jtop10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtop10MouseClicked
FrmRanking f =new FrmRanking();
f.setVisible(true);
this.dispose();
}//GEN-LAST:event_jtop10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                    new MENU().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jJugadores;
    private javax.swing.JLabel jJugar;
    private javax.swing.JLabel jJugar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jtop10;
    // End of variables declaration//GEN-END:variables
}
